package psedit

type Item uint8

const (
	Nothing Item = 0
	MaxItem Item = 64
)

var Items = map[Item]string{
	Nothing: "[nothing]",
	1:       "Wooden Cane",
	2:       "Short Sword",
	3:       "Iron Sword",
	4:       "Wand",
	5:       "Iron Fang",
	6:       "Iron Axe",
	7:       "Titanium Sword",
	8:       "Ceramic Sword",
	9:       "Needle Gun",
	10:      "Silver Fang",
	11:      "Heat Gun",
	12:      "Light Saber",
	13:      "Laser Gun",
	14:      "Laconium Sword",
	15:      "Laconium Axe",
	16:      "Lithium Armor",
	17:      "White Mantle",
	18:      "Light Suit",
	19:      "Iron Armor",
	20:      "Thick Fur",
	21:      "Zirconium Armor",
	22:      "Diamond Armor",
	23:      "Laconium Armor",
	24:      "Fraid Mantle",
	25:      "Lithium Shield",
	26:      "Bronze Shield",
	27:      "Iron Shield",
	28:      "Ceramic Shield",
	29:      "Glove",
	30:      "Laser Shield",
	31:      "Mirror Shield",
	32:      "Lacomium Shield",
	33:      "Land Rover",
	34:      "Hovercraft",
	35:      "Ice Digger",
	36:      "Cola",
	37:      "Burger",
	38:      "Flute",
	39:      "Flash",
	40:      "Escaper",
	41:      "Transfer",
	42:      "Magic Hat",
	43:      "Alsulin",
	44:      "Polymtrl",
	45:      "Dungeon Key",
	46:      "Sphere",
	47:      "Torch",
	48:      "Prism",
	49:      "Nuts",
	50:      "Hapsby",
	51:      "Road Pass",
	52:      "Passport",
	53:      "Compass",
	54:      "Cake",
	55:      "Letter",
	56:      "Laconium Pot",
	57:      "Magic Lamp",
	58:      "Amber Eye",
	59:      "Gas Shield",
	60:      "Crystal",
	// The following items are not usable.
	61: "M System",
	62: "Miricle Key",
	63: "Zillion",
	64: "Secrets",
}
